[metadata]
name = "git-repos"
requirements = ["fd", "git"]

[source]
command = "fd -g .git -HL -t d -d 10 --prune ~/src --exec dirname '{}'"
no_sort = true
display = "{split:/:-1}"

[preview]
command = "cd '{}'; git remote -v && echo && git worktree list | sed \"s|$HOME|~|g\" && echo && git branch -a --sort=-committerdate"
footer = "My Footer: '{}'"

[keybindings]
enter = "actions:cd"
ctrl-e = "actions:edit"

[actions.cd]
description = "Open a new shell in the selected repo"
command = "cd '{}' && $SHELL"
mode = "execute"

[actions.worktrees]
description = "See worktrees for repo"
command = "cd '{}' && tv git-worktrees"
mode = "execute"

[actions.edit]
description = "Open repo in vscode"
command = "code '{}'"
shell = "bash"
mode = "execute"
