[metadata]
name = "git-repos"
requirements = ["fd", "git"]

[source]
command = "fd -g .git -HL -t d -d 10 --prune ~/src --exec dirname '{}'"
display = "{split:/:-1}"

[preview]
command = "cd '{}'; git remote -v && echo && git worktree list | sed \"s|$HOME|~|g\" && echo && git branch -a"
footer = "My Footer: '{}'"

[keybindings]
enter = "actions:cd"
ctrl-e = "actions:edit"

[actions.cd]
description = "Open a new shell in the selected repository"
command = "cd '{}' && $SHELL"
mode = "execute"

[actions.edit]
description = "Open the repository in editor"
command = "${EDITOR:-vim} '{}'"
shell = "bash"
mode = "execute"
