# TMUX configuration

# remap prefix from 'Ctrltrl-b' to 'Ctrl-Space'
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# reload config file
bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using alt+hjkl without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Mouse
# =====
# enable mouse
set -g mouse on
# scroll 1 line per wheel tick instead of a big jump
bind -T copy-mode-vi WheelUpPane   send-keys -X -N 1 scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X -N 1 scroll-down

# don't rename windows automatically
# set window names using the comma [,] key
set-option -g allow-rename off

# number windows from 1 (instead of 0)
# also renumber windows when a window in the middle gets terminated
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# move status bar to the bottom
set -g status-position bottom

# LazyGit popup
bind -n C-g display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"
# Help popup
bind C-h display-popup -w 80% -h 80% -E "thelp"

