## tmux configuration ##

# Remap prefix from 'Ctrltrl-b' to 'Ctrl-Space' because it is easier to press.
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Reload config file with prefix,r
bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

# In tmux, "windows" are what you probably think of as tabs in other programs.
# "Panes" are the individual splits inside of one window.
# Hierarchy: sessions > windows > panes

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Switch panes using alt+hjkl without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Enable mouse
set -g mouse on
# Scroll 1 line per wheel tick instead of a big jump
bind -T copy-mode-vi WheelUpPane   send-keys -X -N 1 scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X -N 1 scroll-down

# Don't rename windows automatically.
# Set window names using the comma [,] key.
set-option -g allow-rename off

# Number windows from 1 instead of 0, makes selecting first tab easier.
# Also, renumber the windows when a window in the middle gets terminated.
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Move status bar to the bottom.
set -g status-position bottom
