# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: "/btw"
    replace: "General question (no changes required): "

  - trigger: "/dti"
    replace: "https://github.com/dotnet/docker-tools/issues/"
  - trigger: "/dtp"
    replace: "https://github.com/dotnet/dotnet-tools/pulls/"

  - trigger: "/ddi"
    replace: "https://github.com/dotnet/dotnet-docker/issues/"
  - trigger: "/ddp"
    replace: "https://github.com/dotnet/dotnet-docker/pulls/"
  - trigger: "/ddd"
    replace: "https://github.com/dotnet/dotnet-docker/discussions/"

  - trigger: "/dfi"
    replace: "https://github.com/microsoft/dotnet-framework-docker/issues/"
  - trigger: "/dfp"
    replace: "https://github.com/microsoft/dotnet-framework-docker/pulls/"
  - trigger: "/dfd"
    replace: "https://github.com/microsoft/dotnet-framework-docker/discussions/"
